package config

const USER_DEFINED_DATA_FOLDER = "USER_DEFINED_DATA_FOLDER"
const LIST_AFTER_ADDING_TODO = "LIST_AFTER_ADDING_TODO"
const LIST_AFTER_EDITING_TODO = "LIST_AFTER_EDITING_TODO"
const LIST_AFTER_REMOVING_TODO = "LIST_AFTER_REMOVING_TODO"
